/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "mensaje.h"

bool_t
print_1_svc(char *username, char *operation, char *date, char *file, int *result,  struct svc_req *rqstp)
{
	bool_t retval = 0;
	// Devuelve 1 si imprime fecha, 0 si no la imprime
	if (file != NULL)
	{
		printf("%s %s %s %s\n", username, operation, date, file);
		*result = 1;
	}
	else
	{
		printf("%s %s %s\n", username, operation, date);
		*result = 0;
	}
	return retval;
}

int
list_service_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
