/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "mensaje.h"

bool_t
xdr_print_1_argument (XDR *xdrs, print_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->username, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operation, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->date, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->file, 256))
		 return FALSE;
	return TRUE;
}
