/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MENSAJE_H_RPCGEN
#define _MENSAJE_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct print_1_argument {
	char *username;
	char *operation;
	char *date;
	char *file;
};
typedef struct print_1_argument print_1_argument;

#define LIST_SERVICE 99
#define LIST_SERVICE_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define print 0
extern  enum clnt_stat print_1(char *, char *, char *, char *, int *, CLIENT *);
extern  bool_t print_1_svc(char *, char *, char *, char *, int *, struct svc_req *);
extern int list_service_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define print 0
extern  enum clnt_stat print_1();
extern  bool_t print_1_svc();
extern int list_service_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_print_1_argument (XDR *, print_1_argument*);

#else /* K&R C */
extern bool_t xdr_print_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MENSAJE_H_RPCGEN */
