/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "mensaje.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
print_1(char *username, char *operation, char *date, char *file, int *clnt_res,  CLIENT *clnt)
{
	print_1_argument arg;
	arg.username = username;
	arg.operation = operation;
	arg.date = date;
	arg.file = file;
	return (clnt_call (clnt, print, (xdrproc_t) xdr_print_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
